<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="PW-HAN-063" name="automation.project3ds.oldTest.BrickWidget_OFF1_1v5" tests="2" failures="0" timestamp="29 Aug 2019 09:13:23 GMT" time="25.800" errors="1">
  <testcase name="execute" time="0.000" classname="automation.project3ds.oldTest.BrickWidget_OFF1_1v5">
    <skipped/>
  </testcase> <!-- execute -->
  <testcase name="setUp" time="25.800" classname="automation.project3ds.oldTest.BrickWidget_OFF1_1v5">
    <error type="com.codoid.products.exception.FilloException" message="No records found">
      <![CDATA[com.codoid.products.exception.FilloException: No records found
at com.codoid.products.fillo.Recordset.<init>(Recordset.java:40)
at com.codoid.products.fillo.Connection.executeQuery(Connection.java:69)
at automation.project3ds.Action.getTestData(Action.java:331)
at automation.project3ds.oldTest.BrickWidget_OFF1_1v5.setUp(BrickWidget_OFF1_1v5.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- setUp -->
</testsuite> <!-- automation.project3ds.oldTest.BrickWidget_OFF1_1v5 -->
