<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="PW-HAN-063" name="p1.Case25_32_WidgetBrick_1v6_Test_ValidateOthers" tests="5" failures="1" timestamp="04 Oct 2019 09:40:01 GMT" time="90.637" errors="0">
  <testcase name="firstNameAsNumber" time="16.286" classname="p1.Case25_32_WidgetBrick_1v6_Test_ValidateOthers"/>
  <testcase name="emailWithOutAt" time="25.728" classname="p1.Case25_32_WidgetBrick_1v6_Test_ValidateOthers"/>
  <testcase name="emailWithOutDot" time="16.580" classname="p1.Case25_32_WidgetBrick_1v6_Test_ValidateOthers"/>
  <testcase name="lastNameAsNumber" time="16.269" classname="p1.Case25_32_WidgetBrick_1v6_Test_ValidateOthers"/>
  <testcase name="nameAsNumber" time="15.774" classname="p1.Case25_32_WidgetBrick_1v6_Test_ValidateOthers">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	[Text value] expected [Please check firstname/last name] but found [Please check first namePlease check last name]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
[Text value] expected [Please check firstname/last name] but found [Please check first namePlease check last name]
at automation.project3ds.Assertion.end(Assertion.java:26)
at p1.Case25_32_WidgetBrick_1v6_Test_ValidateOthers.nameAsNumber(Case25_32_WidgetBrick_1v6_Test_ValidateOthers.java:67)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- nameAsNumber -->
</testsuite> <!-- p1.Case25_32_WidgetBrick_1v6_Test_ValidateOthers -->
